// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProDeal.Infrastructure.Data;

#nullable disable

namespace ProDeal.Infrastructure.Migrations
{
    [DbContext(typeof(ProDealDbContext))]
    partial class ProDealDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProDealChallenge.Domain.Models.FolderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("external_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<int?>("ParentExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_external_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("Index_external_id");

                    b.HasIndex("ParentExternalId");

                    b.ToTable("FolderItems");
                });

            modelBuilder.Entity("ProDealChallenge.Domain.Models.FolderItem", b =>
                {
                    b.HasOne("ProDealChallenge.Domain.Models.FolderItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentExternalId")
                        .HasPrincipalKey("ExternalId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ProDealChallenge.Domain.Models.FolderItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
